[DEFAULT]
# App related
APP_NAME = 'customragpipeline'
PORT = 5550

# Log Related
log_level = 'INFO'

# Data Related
# [To-Do] absolute paths only for testing; to be changed for prod
raw_file_path = "../../../Downloads/ConceptsofBiology-WEB.pdf"
collection = "customragpipeline"

# Embedding Model
# [To-Do] absolute paths only for testing; to be changed for prod
embed_model_path = "../../../Downloads/all-mpnet-base-v2"

# LLM
# [To-Do] absolute paths only for testing; to be changed for prod
llm_model_path = "../../../Downloads/llama-2-13b-chat.Q4_0.gguf"

